package sk.lkrnac.discorg.model.cache;

import sk.lkrnac.discorg.general.constants.MediaIssueCode;
import sk.lkrnac.discorg.model.interfaces.IMediaIssue;

/**
 * Is used for tracking various problems on media storages.
 * 
 * @author sitko
 */
// NOPMD: Complexity is because of equals method generated by Eclipse
@SuppressWarnings("PMD.CyclomaticComplexity")
public class MediaIssue implements IMediaIssue {

	private static final int HASH_CODE_HELPER_2 = 1237;
	private static final int HASH_CODE_HELPER_1 = 1231;
	private final String sourceAbsolutePath;
	private final MediaIssueCode issueCode;
	private final boolean error;
	private final String relativePath;
	private String errorMessage;

	/**
	 * Creates new {@link MediaIssue} instance.
	 * 
	 * @param sourceAbsolutePath
	 *            - ID of issue source
	 * @param issueCode
	 *            - media issue code
	 * @param relativePath
	 *            - Relative path of issue source
	 * @param error
	 *            - indicates is issue is error or warning
	 */
	public MediaIssue(String sourceAbsolutePath, MediaIssueCode issueCode, String relativePath, boolean error) {
		this.sourceAbsolutePath = sourceAbsolutePath;
		this.issueCode = issueCode;
		this.error = error;
		this.relativePath = relativePath;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public final String getSourceAbsolutePath() {
		return sourceAbsolutePath;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public final MediaIssueCode getIssueCode() {
		return issueCode;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public final boolean isError() {
		return error;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public final String getRelativePath() {
		return relativePath;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public final String getErrorMessage() {
		return errorMessage;
	}

	/**
	 * @param errorMessage
	 *            optional error message belonging to the issue
	 */
	public final void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

	/**
	 * Generated by Eclipse.
	 * <p>
	 * {@inheritDoc}
	 */
	@Override
	public final String toString() {
		return "MediaIssue [relativePath=" + relativePath + ", issueCode=" + issueCode + //$NON-NLS-1$ //$NON-NLS-2$ 
				", error=" + error //$NON-NLS-1$ 
				+ ", sourceAbsolutePath=" + sourceAbsolutePath + "]"; //$NON-NLS-1$ //$NON-NLS-2$
	}

	/**
	 * Generated by Eclipse.
	 * <p>
	 * {@inheritDoc}
	 */
	@Override
	@SuppressWarnings("PMD")
	public final int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (error ? HASH_CODE_HELPER_1 : HASH_CODE_HELPER_2);
		result = prime * result + ((errorMessage == null) ? 0 : errorMessage.hashCode());
		result = prime * result + ((issueCode == null) ? 0 : issueCode.hashCode());
		result = prime * result + ((relativePath == null) ? 0 : relativePath.hashCode());
		result = prime * result + ((sourceAbsolutePath == null) ? 0 : sourceAbsolutePath.hashCode());
		return result;
	}

	/**
	 * Generated by Eclipse.
	 * <p>
	 * {@inheritDoc}
	 */
	// CHECKSTYLE:OFF
	@SuppressWarnings("PMD")
	@Override
	public final boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MediaIssue other = (MediaIssue) obj;
		if (error != other.error)
			return false;
		if (errorMessage == null) {
			if (other.errorMessage != null)
				return false;
		} else if (!errorMessage.equals(other.errorMessage))
			return false;
		if (issueCode != other.issueCode)
			return false;
		if (relativePath == null) {
			if (other.relativePath != null)
				return false;
		} else if (!relativePath.equals(other.relativePath))
			return false;
		if (sourceAbsolutePath == null) {
			if (other.sourceAbsolutePath != null)
				return false;
		} else if (!sourceAbsolutePath.equals(other.sourceAbsolutePath))
			return false;
		return true;
	}
	// CHECKSTYLE:ON

}
