package net.lkrnac.discorg.model.treestorage.node;

import net.lkrnac.discorg.model.interfaces.INodeStatus;

/**
 * Represents generic status of the node.<br>
 * Indicates if the folder contains some media files
 * 
 * @author sitko
 */
public class NodeStatus implements INodeStatus {
	/** Folder does not contain media files. */
	public static final NodeStatus NONE = new NodeStatus(0, "status-file.png"); //$NON-NLS-1$
	/** Folder contains lossy media files. */
	public static final NodeStatus LOSSY = new NodeStatus(5, "status-lossy.png"); //$NON-NLS-1$
	/** Folder contains loss-less. */
	public static final NodeStatus LOSSLESS = new NodeStatus(5, "status-lossless.png"); //$NON-NLS-1$

	private final String iconName;
	private final int severity;

	/**
	 * Creates instance of node status.
	 * 
	 * @param severity
	 *            severity of the status (status with higher severity will be
	 *            populated to parent nodes)
	 * @param iconName
	 *            name of the icon that
	 */
	protected NodeStatus(int severity, String iconName) {
		this.severity = severity;
		this.iconName = iconName;
	}

	/**
	 * {@inheritDoc}
	 */
	public final int getSeverity() {
		return severity;
	}

	/**
	 * {@inheritDoc}
	 */
	public final String getIconName() {
		return iconName;
	}

	/**
	 * Generated by Eclipse.
	 * <p>
	 * {@inheritDoc}
	 */
	@Override
	public final String toString() {
		return "NodeStatus [iconName=" + iconName + //$NON-NLS-1$
				", severity=" + severity + "]"; //$NON-NLS-1$ //$NON-NLS-2$
	}
}
